#!/bin/sh
echo
if [ -e .commit ]
	then
	rm .commit
	mkdir -p include
	echo "#ifndef _LCPTOOLS_HO_H_" > include/lcptools_ho.h
	echo "#define _LCPTOOLS_HO_H_" >> include/lcptools_ho.h

	for hfile in lps.h encoding.h core.h; do
		cat $hfile | grep -v "#include \""  >> include/lcptools_ho.h
	done

	echo "#ifdef LCPTOOLS_IMPL"  >> include/lcptools_ho.h
	
	for cfile in lps.c encoding.c core.c; do
		cat $cfile | grep -v "#include \""  >> include/lcptools_ho.h
	done

	echo "#endif" >> include/lcptools_ho.h
	echo "#endif" >> include/lcptools_ho.h
	
	git add include/lcptools_ho.h
	git commit --amend -C HEAD --no-verify
fi
exit

